### ISSUE TITLE
Mod says "Object Reference not set to an instance of an object" upon loading a new file.

### ISSUE THREAD

**Issue by mikukat** [jaschaephraim/rimsaga-issues#5]
https://gist.github.com/HugsLibRecordKeeper/25a874210fb97a58593685da8ca5774c this is the error log i get when loading the game, the mod is by itself xD all i have besides it enabled is biotech dlc and the mods required to run this mod. Any help figuring out what could possibly be the issue is much appreciated.

**Comment by jaschaephraim** [comment]
Just updated to v1.0.1, should be resolved. Please let me know if it's not and thanks for the report
